---
engines:
  eslint:
    enabled: true
  rubocop:
    config:
      file: .rubocop.yml
    enabled: true
ratings:
  paths:
  - 'app/**/*'
  - 'lib/**/*'
  - '**.rb'
exclude_paths:
- config/
- db/
- vendor/
