codeclimate:
  script:
    - docker info
    - 'docker run --interactive --rm --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate engines:install'
    - 'docker run --interactive --rm --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f text >> output.log'
    - 'cat output.log'
    - 'cat output.log | (grep "Found 0 issues" || exit 123 && exit 0)'
  stage: test
  tags:
    - codeclimate
